### ISSUE TITLE
resizing website causes modal to be off center

### ISSUE THREAD

**Issue by eclair4151** [dennisss/chess#37]
![screenshot from 2016-01-27 12 31 37](https://cloud.githubusercontent.com/assets/3183738/12622130/ef7c521c-c4f1-11e5-9bce-876d91afe4fc.png)

**Comment by dmz38** [comment]
Fixed and pushed issue by changing CSS to 98%.

**Comment by dennisss** [comment]
The modals for the other pages are still not centered

**Comment by dmz38** [comment]
http://media1.giphy.com/media/sIE0hveuiwCNG/giphy.gif

**Comment by dennisss** [comment]
I think the issue may be that the chessboard is not centering
![alt text](http://goo.gl/274hKS "Chess Width Issue")

**Comment by dmz38** [comment]
This seems actually fixed again!
