### ISSUE TITLE
UserList Doesn't Sync

### ISSUE THREAD

**Issue by dmz38** [dennisss/chess#46]
Seems as though with the current build, the changes don't sync.

**Comment by dennisss** [comment]
I tried it with a minimal set of code as below, and USERLIST is logged to multiple browsers' consoles. Can you check if that works on your computer and if not, please provide further info in replicating this bug?

> Client.proc.call('join', {room: 'Hello', name: 'Dennis', level: 'Jedi'}, function(err, data){
> 	console.log(err);
>	console.log(data);
> })
> Client.socket.on('userlist', function(data){
> 	console.log('USERLIST')
> 	console.log(data);
> });

**Comment by dmz38** [comment]
OK, sync seems to work.  Right now, leaving the room doesn't seem to be possible.

For example, with the latest push of the code, I have a leave room function when the back button is pressed.  That doesn't result in the removal of the player from the other screens.  We should be doing something so that we can in fact remove them from the "available players" list.

**Comment by dmz38** [comment]
Committing and closing ticket, creating new one for new issue.
