### ISSUE TITLE
Add/Fix functionality for users to be able to be taken off of the available users queue

### ISSUE THREAD

**Issue by dmz38** [dennisss/chess#47]
Currently, there is a leave function.  However, this only seems to apply to rooms, and doesn't work for if the player "accepts" a game and moves on.

**Comment by dennisss** [comment]
Closing the browser should now work, but I will need to improve it to allow reconnects when there is a bad connection.

**Comment by dmz38** [comment]
Tested (manual and code) and passes!  Closing ticket.
