### ISSUE TITLE
Can't request game after another game failed

### ISSUE THREAD

**Issue by tessmichi** [dennisss/chess#58]
Just like with issue "https://github.com/dennisss/chess/issues/52"

That issue has been fixed, but now here is what happens

Specific example:
Tess requested a game with Tedd
Tedd declined the game
Now when Tess OR Tedd tries to start a game with the other one, the loading screen comes up right away then goes away as if the other instantly declined it.

Setting to 1.0 release since it isn't time-sensitive to being done in the next few days.

**Comment by dmz38** [comment]
Confirmed bug.  Assigning to Zach because then he can become familiar with the API.

**Comment by dmz38** [comment]
Confirmed fix.  Issue closed.
