### ISSUE TITLE
Weird cutoff menu when selecting opponent

### ISSUE THREAD

**Issue by eclair4151** [dennisss/chess#60]
When i click select opponent i get this weird cutoff menu without a way to scroll down or cancel
![screenshot from 2016-02-11 15 46 48](https://cloud.githubusercontent.com/assets/3183738/12990181/e679bc2c-d0d6-11e5-849d-b15fe720fd97.png)

**Comment by dmz38** [comment]
This is a 1366x768 issue.  Will investigate, but isn't a P1 issue.

*​Dan Ziegler*
CCI Peer Mentor & Teaching Assistant
President & Founder, DUCSTeach
Computer Science Major
Pennoni Honors College
Drexel University Class of 2017
dmz38@drexel.edu
dan.dmzapps.com

**Comment by dmz38** [comment]
Can you test on https://friendlychess.xyz?  We should enable scrolling now by default so this shouldn't be an issue.

**Comment by dmz38** [comment]
Tested (manual) and passes!  Closing ticket.
