### ISSUE TITLE
text color is incorrect when copying text

### ISSUE THREAD

**Issue by eclair4151** [dennisss/chess#61]
![screenshot from 2016-02-11 15 49 57](https://cloud.githubusercontent.com/assets/3183738/12990223/356437c2-d0d7-11e5-8d60-a2c43bc452db.png)

**Comment by dmz38** [comment]
​This component is being removed.

- NOFIX​

*​Dan Ziegler*
CCI Peer Mentor & Teaching Assistant
President & Founder, DUCSTeach
Computer Science Major
Pennoni Honors College
Drexel University Class of 2017
dmz38@drexel.edu
dan.dmzapps.com

**Comment by dmz38** [comment]
Removed.
