### ISSUE TITLE
Cannot click game actions drop up while waiting for turn

### ISSUE THREAD

**Issue by dennisss** [dennisss/chess#67]
Can't click forfeit, undo, draw, etc. while waiting

**Comment by dmz38** [comment]
I don't think you should.  So I don't think this is a bug.  You should only
be able to forfeit and draw when it is your turn.

*​Dan Ziegler*
CCI Peer Mentor & Teaching Assistant
President & Founder, DUCSTeach
Computer Science Major
Pennoni Honors College
Drexel University Class of 2017
dmz38@drexel.edu
dan.dmzapps.com

**Comment by dmz38** [comment]
Agreed by team.  Nofix.
