### ISSUE TITLE
cant cancel random opponent request and gets stuck here

### ISSUE THREAD

**Issue by eclair4151** [dennisss/chess#73]
![screenshot from 2016-03-07 19 15 01](https://cloud.githubusercontent.com/assets/3183738/13587880/2c5bf7a2-e499-11e5-97a7-63782e26f01a.png)

**Comment by tessmichi** [comment]
@eclair4151 - does it auto cancel itself after you wait a bit? The amount of time before it autocancels should be 20 seconds

**Comment by dmz38** [comment]
@eclair4151 this should be working now.  Care to try it again?
